site_name: GEM-in-a-Box Project Documentation
site_description: A Dataset Repository

repo_name: GEM-in-a-Box-dataset-repository-template
repo_url: https://github.com/hakaiinstitute/gem-in-a-box-dataset-repository-template

theme:
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  name: material
  logo: logos/hakai-logo.png
  custom_dir: docs/.overrides
  icon:
    repo: fontawesome/brands/github 
  features:
    - search.suggest
    - search.highlight
    - search.share

markdown_extensions:
  - attr_list
  - def_list
  - tables
  - pymdownx.highlight:
      use_pygments: false
  - pymdownx.snippets
  - pymdownx.superfences
  - md_in_html

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: repo.url

footer_logos:
  - src: logos/Ocean-Decade-logo-transparent.png
    href: https://hakai.org
    alt: Ocean Decade
  - src: logos/ocean_decade_collaborative_center_for_the_northeast_pacific_logo.jpeg
    href: https://hakai.org
    alt: Ocean Decade Collaborative Center for the Northeast Pacific
  - src: logos/tula-logo.png
    href: https://tula.org
    alt: Tula Foundation
  - src: logos/hakai-logo.png
    href: https://hakai.org
    alt: Hakai Institute

extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - offline

