site_name: GEM-in-a-Box Project Documentation
site_description: A Dataset Repository

repo_url: https://github.com/hakaiinstitute/gem-in-a-box-dataset-repository-template
edit_uri: blob/main/docs/

theme:
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  name: material
  logo: logos/logo.png
  custom_dir: docs/.overrides
  features:
    - search.suggest
    - search.highlight
    - search.share
    - navigation.footer

markdown_extensions:
  - attr_list
  - def_list
  - tables
  - pymdownx.highlight:
      use_pygments: false
  - pymdownx.snippets
  - pymdownx.superfences
  - md_in_html

extra_css:
  - stylesheets/extra.css

plugins:
  - search
